[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 1

[[main]]
  identifier = "archives"
  name = "Archives"
  url = "archives"
  weight = 2

[[main]]
  identifier = "presentations"
  name = "Presentations"
  url = "presentations"
  weight = 3

[[main]]
  identifier = "gallery"
  name = "Gallery"
  url = "gallery"
  weight = 4
    
[[main]]
  parent = "gallery"
  name = "Illustrations"
  url = "gallery/illustrations"

[[main]]
  parent = "gallery"
  name = "Photography"
  url = "gallery/photography"

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 5

[[main]]
  identifier = "projects"
  name = "Projects"
  url = "projects"
  weight = 6

[[main]]
  identifier = "reviews"
  name = "Reviews"
  url = "reviews"
  weight = 7
